/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-12-07 01:07:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class replyTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/myJavaDev/MySpring5Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AMB/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/myJavaDev/MySpring5Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AMB/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../myinclude/myheader.jsp", Long.valueOf(1638413233478L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1635826048185L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!--  \r\n");
      out.write("    Document Title\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <title>ALL MY BEAUTY</title>\r\n");
      out.write("    <!--  \r\n");
      out.write("    Favicons\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/apple-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/apple-icon-60x60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/apple-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/apple-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/apple-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/apple-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/apple-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/apple-icon-152x152.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/apple-icon-180x180.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/android-icon-192x192.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/favicon-96x96.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/manifest.json\">\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicons/ms-icon-144x144.png\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("     <!--  \r\n");
      out.write("    JavaScripts\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/jquery/dist/jquery.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/wow/dist/wow.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/isotope/dist/isotope.pkgd.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/imagesloaded/imagesloaded.pkgd.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/flexslider/jquery.flexslider.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owl.carousel/dist/owl.carousel.min.js\"></script>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/magnific-popup/dist/jquery.magnific-popup.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/simple-text-rotator/jquery.simple-text-rotator.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("    <!--  \r\n");
      out.write("    Stylesheets\r\n");
      out.write("    =============================================\r\n");
      out.write("    -->\r\n");
      out.write("    <!-- Default stylesheets-->\r\n");
      out.write("    <link type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Template specific stylesheets-->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Volkhov:400i\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/animate.css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/components-font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/et-line-font/et-line-font.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/flexslider/flexslider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owl.carousel/dist/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owl.carousel/dist/assets/owl.theme.default.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/magnific-popup/dist/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/simple-text-rotator/simpletextrotator.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Main stylesheet and color file-->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link id=\"color-scheme\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/colors/default.css\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body data-spy=\"scroll\" data-target=\".onpage-navigation\" data-offset=\"60\">\r\n");
      out.write("      <div class=\"page-loader\">\r\n");
      out.write("        <div class=\"loader\">Loading...</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <nav class=\"navbar navbar-custom navbar-fixed-top navbar-transparent\" role=\"navigation\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"navbar-header\">\r\n");
      out.write("            <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\"#custom-collapse\"><span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button><a class=\"navbar-brand\" href=\"index_shop.html\">ALL MY BEAUTY</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"custom-collapse\">\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("              <li><a href=\"index_shop.html\">Home</a></li>\r\n");
      out.write("              <li><a href=\"index_shop.html\">로그인</a></li>\r\n");
      out.write("              <li><a href=\"index_shop.html\">회원가입</a></li>\r\n");
      out.write("              <li><a href=\"index_shop.html\">장바구니</a></li>\r\n");
      out.write("              <li><a href=\"index_shop.html\">Q&A</a></li>\r\n");
      out.write("              <li><a href=\"index_shop.html\">마이페이지</a></li>\r\n");
      out.write("              <!--li.dropdown.navbar-cart-->\r\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown')-->\r\n");
      out.write("              <!--        span.icon-basket-->\r\n");
      out.write("              <!--        |-->\r\n");
      out.write("              <!--        span.cart-item-number 2-->\r\n");
      out.write("              <!--    ul.dropdown-menu.cart-list(role='menu')-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\r\n");
      out.write("              <!--                .navbar-cart-img-->\r\n");
      out.write("              <!--                    a(href='#')-->\r\n");
      out.write("              <!--                        img(src='assets/images/shop/product-9.jpg', alt='')-->\r\n");
      out.write("              <!--                .navbar-cart-title-->\r\n");
      out.write("              <!--                    a(href='#') Short striped sweater-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\r\n");
      out.write("              <!--                    br-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .navbar-cart-item.clearfix-->\r\n");
      out.write("              <!--                .navbar-cart-img-->\r\n");
      out.write("              <!--                    a(href='#')-->\r\n");
      out.write("              <!--                        img(src='assets/images/shop/product-10.jpg', alt='')-->\r\n");
      out.write("              <!--                .navbar-cart-title-->\r\n");
      out.write("              <!--                    a(href='#') Colored jewel rings-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    span.cart-amount 2 &times; $119.00-->\r\n");
      out.write("              <!--                    br-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    strong.cart-amount $238.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .clearfix-->\r\n");
      out.write("              <!--                .cart-sub-totle-->\r\n");
      out.write("              <!--                    strong Total: $476.00-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .clearfix-->\r\n");
      out.write("              <!--                a.btn.btn-block.btn-round.btn-font-w(type='submit') Checkout-->\r\n");
      out.write("              <!--li.dropdown-->\r\n");
      out.write("              <!--    a.dropdown-toggle(href='#', data-toggle='dropdown') Search-->\r\n");
      out.write("              <!--    ul.dropdown-menu(role='menu')-->\r\n");
      out.write("              <!--        li-->\r\n");
      out.write("              <!--            .dropdown-search-->\r\n");
      out.write("              <!--                form(role='form')-->\r\n");
      out.write("              <!--                    input.form-control(type='text', placeholder='Search...')-->\r\n");
      out.write("              <!--                    |-->\r\n");
      out.write("              <!--                    button.search-btn(type='submit')-->\r\n");
      out.write("              <!--                        i.fa.fa-search-->\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".txtBoxCmt, .txtBoxComment {\r\n");
      out.write("	overflow: hidden; resize: vertical; min-height: 100px; color: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("	<div class=\"col-lg-12\">\r\n");
      out.write("		<div class=\"panel panel-default\">\r\n");
      out.write("			<div class=\"panel-heading\">\r\n");
      out.write("			    <p style=\"margin-bottom: 0px; font-size: 16px;\">\r\n");
      out.write("	                    <strong style=\"padding-top: 2px;\">\r\n");
      out.write("	                        <span>&nbsp;</span>\r\n");
      out.write("	                        <button type=\"button\" id=\"btnChgCmtReg\" class=\"btn btn-border-d btn-round\">댓글 작성</button>\r\n");
      out.write("	                        <button type=\"button\" id=\"btnRegCmt\" class=\"btn btn-w btn-round\" style=\"display:none\">댓글 등록</button>\r\n");
      out.write("	                        <button type=\"button\" id=\"btnCancelRegCmt\" class=\"btn btn-danger btn-round\" style=\"display:none\">취소</button>\r\n");
      out.write("	                    </strong>\r\n");
      out.write("	            </p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"panel-body\">\r\n");
      out.write("\r\n");
      out.write("		                <div class=\"form-group\" style=\"margin-bottom: 5px;\">\r\n");
      out.write("		                    <textarea class=\"form-control input-lg\" name=\"rcontent\"\r\n");
      out.write("		                               placeholder=\"댓글작성을 원하시면,&#10;댓글 작성 버튼을 클릭해주세요.\"\r\n");
      out.write("		                               readonly=\"readonly\"\r\n");
      out.write("		                    ></textarea>\r\n");
      out.write("		                </div>\r\n");
      out.write("		                <hr style=\"margin-top: 10px; margin-bottom: 10px;\">\r\n");
      out.write("		                \r\n");
      out.write("		                <ul class=\"chat\"> \r\n");
      out.write("		                <li class=\"left clearfix commentLi\" data-bno=\"123456\" data-cno=\"12\">\r\n");
      out.write("		                	<div>\r\n");
      out.write("		                		<div>\r\n");
      out.write("		                			<span class=\"header info-rwriter\">\r\n");
      out.write("		                				<strong class=\"primary-font\">user00</strong>\r\n");
      out.write("		                				<span>&nbsp;</span>\r\n");
      out.write("		                			</span>\r\n");
      out.write("		                			<p>1111</p>\r\n");
      out.write("		                		</div>\r\n");
      out.write("		                		<div class=\"btnsComment\" style=\"margin-bottom:10px\">\r\n");
      out.write("		                			<button type=\"button\" style=\"display:in-block\"\r\n");
      out.write("		                					class=\"btn btn-g btn-round btn-sm\" type=\"button\">답글 작성</button>\r\n");
      out.write("		                			<button type=\"button\" style=\"display:none\"\r\n");
      out.write("		                					class=\"btn btn-danger btn-round\" type=\"button\">답글 등록</button>\r\n");
      out.write("		                			<hr class=\"txtBoxCmtHr\" style=\"margin-top:10px; margin-bottom:10px\">\r\n");
      out.write("		                			<textarea class=\"form-control txtBoxCmtMod\" name=\"ccontent\" style=\"margin-bottom:10px\"\r\n");
      out.write("		                					placeholder=\"please insert here\">\r\n");
      out.write("		                			</textarea>\r\n");
      out.write("		                		</div>\r\n");
      out.write("		                	</div>\r\n");
      out.write("		                </li>\r\n");
      out.write("		               </ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<form id=\"frmCmtPagingValue\">\r\n");
      out.write("			<input type='hidden' name='pageNum' value=''/>\r\n");
      out.write("			<input type='hidden' name='rowAmountPerPage' value=''/>\r\n");
      out.write("			\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/mycomment.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	var commentUL = $(\".chat\");\r\n");
      out.write("	var frmCmtPagingValue = $(\"#frmCmtPagingValue\");\r\n");
      out.write("	//댓글 목록 표시 함수\r\n");
      out.write("	function getCmtList(page){\r\n");
      out.write("		myCommentClsr.getCmtList(\r\n");
      out.write("				{bno: bnoValue, page: page || 1},\r\n");
      out.write("				function(replyPagingCreator){\r\n");
      out.write("					console.log(\"서버로부터 전달된 pageNum(BCommentPaging.myRelyPaging.pageNum)\"\r\n");
      out.write("							+ bCommentPagingCreator.bCommentPaging.pagingNum);\r\n");
      out.write("					\r\n");
      out.write("					frmCmtPagingValue.find(\"input[name='pageNum']\")\r\n");
      out.write("									.val(bCommentPagingCreator.bCommentPaging.pageNum);\r\n");
      out.write("					\r\n");
      out.write("					console.log(\"폼에 저장된 페이징 번호 pageNum:\"\r\n");
      out.write("							+ frmCmtPagingValue.find(\"input[name='pageNum']\").val());\r\n");
      out.write("					var str=\"\";\r\n");
      out.write("				})\r\n");
      out.write("				//댓글이 없으면 if문안의 블록이 실행됨 or 중지됨\r\n");
      out.write("		if( (! bCommentPagingCreator.CmtList) || (bCommentPagingCreator.length == 0) ){\r\n");
      out.write("			str += '<li class=\"left clearfix commentLi\" '\r\n");
      out.write("			+	'	style=\"text-align: center; background-color: lightCyan;'\r\n");
      out.write("			+	'   '		height: 35px;margin-bottom: 0px;padding-bottom:0px;'\r\n");
      out.write("			+   '           padding-top:6px;border: 1px dotted;\">'\r\n");
      out.write("			+   '       <strong>등록된 댓글이 없습니다.</strong></li>';\r\n");
      out.write("			commentUl.html(str)\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		//답글표시 for문\r\n");
      out.write("		for (var i = 0, len = bCommentPagingCreator.CmtList.length; i < len; i++){\r\n");
      out.write("			str +='<li class=\"left clearfix commentLi data-bno=\"' + bnoValue\r\n");
      out.write("			+ '\"	data-cno\"'+bCommentPagingCreator.CmtList[i].rno+\"'>'\r\n");
      out.write("			+'        <div>';\r\n");
      out.write("	//댓글에 대한 답글 들여쓰기\r\n");
      out.write("		if(bCommentPagingCreator.CmtList[i].lvl ==1){\r\n");
      out.write("			str+='		<div>';\r\n");
      out.write("		}else if (bCommentPagingCreator.CmtList[i].lvl == 2){\r\n");
      out.write("			str+='        <div style=\"padding-left:25px\">';\r\n");
      out.write("		}else if (bCommentPagingCreator.CmtList[i].lvl == 3){\r\n");
      out.write("			str+='		  <div style=\"padding-left:50px\">';\r\n");
      out.write("		}else if (bCommentPagingCreator.CmtList[i].lvl == 4){\r\n");
      out.write("			str+='		  <div style=\"padding-left:75px\">';\r\n");
      out.write("		}else{\r\n");
      out.write("			str +='       <div style=\"padding-left:100px\">';\r\n");
      out.write("		}\r\n");
      out.write("			str +='          <span class=\"header info-mid\">'\r\n");
      out.write("				+ '              <strong class=\"primary-font\">';\r\n");
      out.write("		if(bCommentPagingCreator.CmtList[i].lvl > 1){\r\n");
      out.write("			str+='                  <i class=\"fa fa-reply fa-fw\"></i>&nbsp;';\r\n");
      out.write("		}\r\n");
      out.write("			str+=					bCommentPagingCreator.CmtList[i].mid\r\n");
      out.write("			   + '              </strong>'\r\n");
      out.write("			   + '              <span>&nbsp;</span>'\r\n");
      out.write("		if(bCommentPagingCreator.CmtList[i].lvl > 1){\r\n");
      out.write("			str +='             <small>&nbsp; 답글</small>'\r\n");
      out.write("		}\r\n");
      out.write("			str +='         <span>'\r\n");
      out.write("				+ '         <p data bno=' + bCommentPagingCreator.CmtList[i].bno\r\n");
      out.write("				+ '            data-rno=' + bCommentPagingCreator.CmtList[i].rno\r\n");
      out.write("				+ '            data-mid=' + bCommentPagingCreator.CmtList[i].mid\r\n");
      out.write("				+ '         >' + bCommentPagingCreator.CmtList[i].rcontent + '</p>'\r\n");
      out.write("				+ '     </div>';\r\n");
      out.write("				+ '    </div>'\r\n");
      out.write("				+ '</li>';\r\n");
      out.write("		}//for-end\r\n");
      out.write("				commentUL.html(str);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		showCmtList(1);\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/board/replyTest.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/board/replyTest.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/replyTest.jsp(6,0) '${pageContext.request.contextPath} '",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath} ",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/board/../myinclude/myheader.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("contextPath");
      // /WEB-INF/views/board/../myinclude/myheader.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/../myinclude/myheader.jsp(4,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
